### ISSUE TITLE
Is it working for you?

### ISSUE THREAD

**Issue by plexus** [plexus/tracer-gui#1]
There were some issues with the first `0.1.0-SNAPSHOT` regarding AOT compilation, so if you tried tracer-gui before 2016-04-09 please upgrade with `lein -U deps`.

You'll need a recent Clojure, the AOT compilation is done with 1.7 so 1.7 or 1.8 should work.

You'll need a recent Java, not sure how recent, I've only tested on 1.8, but JavaFX has seen some major updates in recent versions so that might throw a spanner in the works.

My setup
- Ubuntu 15.10
- java version "1.8.0_77" (OpenJDK)
- Clojure 1.8

If you tried tracer-gui please post your OS/java/clojure versions and whether it worked or not.

**Comment by sveri** [comment]
I do not see the popup anywhere. 

My setup is:
- Ubuntu 15.10
- java version 1.8.0_77-b03 (oracle JDK)
- Clojure 1.8

I tried two things, first, put the trace-ring function around the routes function and second, put it in as middleware, neither of which worked.
